name: Edge Bot Pro

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python bot.py
